# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0015_auto_20160421_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='GistPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('gist_id', models.CharField(default='', help_text='Enter the Gist ID.', max_length=32, verbose_name='Gist ID')),
                ('filename', models.CharField(blank=True, default='', help_text='Optional. Enter the filename, if there are multiple files and you only want to display one.', max_length=32, verbose_name='filename')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GistUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', help_text='Choose the GitHub user for this Gist.', max_length=32, verbose_name='username')),
            ],
        ),
        migrations.AddField(
            model_name='gistpluginmodel',
            name='gist_user',
            field=models.ForeignKey(default=None, help_text='Choose the GitHub user for this Gist.', on_delete=django.db.models.deletion.CASCADE, to='djangocms_gist.GistUser'),
        ),
    ]
